{% set name = "MAPIE" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: 465cf763d62a574fbb855232dd7222fa541c09fa9fdeaedcf6dae1fadcd7d8d3

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.21
    - packaging
    - python >={{ python_min }}
    - scikit-learn <=1.6.0

test:
  imports:
    - mapie
    - mapie.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/MAPIE/
  summary: A scikit-learn-compatible module for estimating prediction intervals.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://mapie.readthedocs.io/en/latest/
  dev_url: https://github.com/scikit-learn-contrib/MAPIE

extra:
  recipe-maintainers:
    - valentin-laurent
    - thibaultcordier
    - tmorzade
    - LacombeLouis
    - gmartinonQM
    - vtaquet
    - vincentblot28
