{% set name = "MAPIE" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: d632d19675063e7319c3cec896bbb61680532bb64ba075b517d375fbf8a875fa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.23
    - packaging
    - python >={{ python_min }}
    - scikit-learn >=1.4

test:
  imports:
    - mapie
    - mapie.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}
    - scikit-learn >=1.4

about:
  home: https://pypi.org/project/MAPIE/
  summary: A scikit-learn-compatible module for estimating prediction intervals.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://mapie.readthedocs.io/en/latest/
  dev_url: https://github.com/scikit-learn-contrib/MAPIE

extra:
  recipe-maintainers:
    - GBrelurut
    - allglc
    - valentin-laurent
    - thibaultcordier
    - tmorzade
    - LacombeLouis
    - gmartinonQM
    - vtaquet
    - vincentblot28
